CONFIG_ASSERT=y # validation
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_SCD4X=y

#CONFIG_SCD4X_FACTORY_RESET_AT_INIT=y
#CONFIG_SCD4X_SELFTEST_AT_INIT=y
CONFIG_SCD4X_MEASURE_MODE_RUNTIME_CHANGE=y

CONFIG_SCD4X_MEASURE_PERIODIC_HPM=y
#CONFIG_SCD4X_MEASURE_PERIODIC_LPM=y
#CONFIG_SCD4X_MEASURE_SINGLE_SHOT=y
